### ISSUE TITLE
AutoSelect Option Visibility Issue

### ISSUE THREAD

**Issue by tenzincopart** [copartit/g2-ops-component-library#141] opened 2018-09-10 17:37 UTC
**Describe the bug**
Options for the AutoSelect is getting hidden below the next section.
AutoSelect is allowing deletion of the selected text partially. - IGNORE THIS
![screen shot 2018 09 10 at 10 27 09 am 2](https://user-images.githubusercontent.com/24234481/45314043-91b70000-b4e5-11e8-8956-d9c5d7d0ac57.png)
![screen shot 2018 09 10 at 10 27 19 am 2](https://user-images.githubusercontent.com/24234481/45314044-91b70000-b4e5-11e8-9243-a04465bf739f.png)

**Comment by tenzincopart** [comment] 2018-09-10 18:39
@colshacol  - the second issue was caused by uk engineering. Thanks @sidharthmehra  for pointing this out. I have asked @revanthCopart  to look at it. Thanks!

**Comment by revanthCopart** [comment] 2018-09-10 19:13
For the second issue that @tenzincopart pointed out, there is no way the UI can fix this. All I am using as of now to prevent that is to check what `onChange` returns and see if there is an option with that text, if not set it to null. But the problem arises when the option is for instance `No`, in which case when you delete `o` it is still a valid option. Is there a way to stop them from editing text and only allowing them to select and provide an `onSelect` callback instead of an `onChange` callback? Also the `onBlur` callback is not returning anything.

**Comment by colshacol** [comment] 2018-09-12 17:07
I have fixed this issue once before for another app soon after I first started. I think it can be 100% fixed by ensuring that a new stacking context is created for the AutoSelect options as well as ensuring that the parent allows overflow, or that the options escape the overflow control.

I will take a look soon.

**Comment by revanthCopart** [comment] 2018-09-19 20:17
Hey Colton. Any update on this? It is causing tensions on the UK Engineering UI ;P

**Comment by colshacol** [comment] 2018-10-12 23:20
Closing this. I have solved it for UK Engineering now, and the cause is not inside of core components. ;)

**Closed by colshacol** 2018-10-12 23:20 UTC
